name: Documentation
on:
  push:
    branches: [ master, main ]


permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme
          pip install numpy~=1.23 matplotlib~=3.5 pandas~=1.3 meshio~=5.3 vtk~=9.2 gmsh~=4.9
          pip install -e .

      - name: Generate API skeleton
        run: |
          # Remove old generated files to ensure a clean TOC
          rm -f docs/dolfin_mech.*.rst
          rm -f docs/modules.rst
          # --separate puts each module (Material, Operator, etc.) on its own page
          # -e tells sphinx to give each module its own file
          sphinx-apidoc -e -o docs/ dolfin_mech/ --no-toc --force --module-first
          # Delete the specific file that is causing the "multiple toctree" conflict since I manually categorised in index
          rm -f docs/dolfin_mech.rst
          # Clean up the titles in all generated .rst files
          sed -i 's/ package//g' docs/*.rst
          sed -i 's/ module//g' docs/*.rst

      - name: Build Sphinx Documentation
        run: |
          sphinx-build -b html docs/ docs/build
          # Critical: tells GitHub not to use Jekyll, allowing underscores in folder names
          touch docs/build/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build
          branch: gh-pages